# Generated by Django 5.1.6 - Corrected initial migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0007_alter_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_url', models.TextField()),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('creation_date', models.DateField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='pet.pet')),
            ],
        ),
    ]
