# Generated by Django 5.1.6 on 2025-03-11 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_url', models.URLField(max_length=254)),
                ('pdf_url', models.URLField(max_length=254)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
