# Generated by Django 5.1.6 on 2025-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='statusAdoption',
            field=models.IntegerField(choices=[(1, 'This pet has family'), (0, 'This pet doesnt have family')], default=0),
        ),
    ]
