# Generated by Django 5.1.6 on 2025-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_statusadoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='statusAdoption',
            field=models.IntegerField(choices=[(1, 'This pet has family'), (0, 'This pet doesnt have family'), (2, 'This pet is looking for a family')], default=0),
        ),
    ]
