# Generated by Django 5.1.6 on 2025-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_statusadoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
