# Generated by Django 5.1.6 on 2025-04-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeQR', '0001_initial'),
        ('pet', '0005_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='qrId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codeQR.codeqr'),
        ),
    ]
