# Generated by Django 5.1.6 - qrId field removed from model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pet_age'),
    ]

    operations = [
    ]
