# Generated by Django 5.1.6 on 2025-03-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Con dueño', 'Con dueño'), ('En adopción', 'En adopción'), ('Desaparecido', 'Desaparecido'), ('Robado', 'Robado')], max_length=20)),
                ('newDate', models.DateField()),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
        ),
    ]
