# Generated by Django 5.1.6 on 2025-03-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('idEmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emitter', to='user.user')),
                ('idReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.user')),
            ],
        ),
    ]
