# Generated by Django 5.1.6 on 2025-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('admin', 'adminstrator'), ('user', 'user')], max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=254)),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='Date when the account was registered')),
            ],
        ),
    ]
