# Generated by Django 5.1.6 on 2025-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Date when the account was registered')),
                ('status', models.IntegerField(choices=[(1, 'The account is active'), (2, 'The account is not active')], default=1)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', max_length=20)),
            ],
        ),
    ]
