# Generated by Django 5.1.6 on 2025-03-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifType', models.CharField(choices=[('Desaparecido_Alrededor', 'Desaparecido Alrededor'), ('Nueva_Mascota', 'Nueva Mascota'), ('Comentario', 'Comentario'), ('Mensaje', 'Mensaje'), ('Otro', 'Otro')], max_length=30)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('notiDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
