# Generated by Django 5.1.6 on 2025-05-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='related_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
