# Generated by Django 5.1.6 on 2025-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='profilePhotoURL',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
